### PR TITLE
Update 40-aria.md

### PR DESCRIPTION
**Pull request by geoffrey-eisenbarth**
Fix js links and add menu button to example.

### CODE REVIEW

**Comment by geoffrey-eisenbarth** [comment]
Oh, I'm actually not sure if the JS link changes are necessary because of [this](https://github.com/bigskysoftware/missing/blob/c6a8a3cde161e5ce01a7c37cc6463db08ff8993d/www/releases/1.1.2.md) (although the js links are currently broken).

I do think adding the `<button>` in the menu example is helpful tho.

**Comment by fkscott** [comment]
I agree about the button. Always good to provide clarity. I do not think the JS changes are necessary in the template though. At least during testing on my local machine, copying those files into `missing-js/` made those components work.

**Comment by geoffrey-eisenbarth** [comment]
@fkscott I'm not particularly familiar with the way this repo is set up. Given your change, what needs to happen for the links to work on the docs website? The release of 1.1.2?

When I have a second, I'll undo the URL changes in this PR, just juggling right now.

**Comment by fkscott** [comment]
Correct, the release of 1.1.2 should fix the links. Making the `missing-js` folder accessible by the website means none of the markup has to change.

**Comment by geoffrey-eisenbarth** [comment]
Okay, should be good. I've never used GitHub to directly edit files and create PRs, so please let me know if something looks off. The only thing in this PR should be adding the button in the tabs example.

**Comment by dz4k** [comment]
unfortunately I missed this PR and applied the same fix myself. Thanks either way for contributing

**Pull request closed without merging**
